---
root: true
env:
  browser: true
  es2022: true
  node: true
ignorePatterns:
  - /*.js
  - vitest.config.ts
plugins:
  - storybook
extends:
  - eslint:recommended
  - next/core-web-vitals
  - standard-with-typescript
  - eslint-config-prettier
  - plugin:storybook/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
rules:
  '@typescript-eslint/no-unnecessary-condition': error
  '@typescript-eslint/restrict-template-expressions':
    - error
    - allowNumber: true
      allowBoolean: true
      allowAny: true
      allowNullish: false
      allowRegExp: true

  semi: off
  comma-dangle: off
  space-before-function-paren: off
  no-case-declarations: off
  indent: off
  multiline-ternary: off
  react/display-name: off
  '@typescript-eslint/explicit-function-return-type': off
