---
root: true
env:
  browser: true
  es2022: true
  node: true
ignorePatterns:
  - /*.js
  - vitest.config.ts
plugins:
  - storybook
  - tailwindcss
extends:
  - eslint:recommended
  - next/core-web-vitals
  - standard-with-typescript
  - eslint-config-prettier
  - plugin:storybook/recommended
  - plugin:tailwindcss/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
rules:
  '@typescript-eslint/no-unnecessary-condition': error
  '@typescript-eslint/restrict-template-expressions':
    - error
    - allowNumber: true
      allowBoolean: true
      allowAny: true
      allowNullish: false
      allowRegExp: true

  semi: off
  react/display-name: off
  import/no-anonymous-default-export: off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/consistent-type-assertions': off
  '@typescript-eslint/consistent-type-definitions': off
  '@typescript-eslint/no-non-null-assertion': off
