printWidth: 138
tabWidth: 2
trailingComma: all
useTabs: false
semi: true
jsxSingleQuote: false
bracketSpacing: true
bracketSameLine: false
singleQuote: true
arrowParens: always
cursorOffset: -1
editorconfig: false
embeddedLanguageFormatting: auto
endOfLine: lf
htmlWhitespaceSensitivity: css
insertPragma: false
