import { LoginButton } from '#/components/LoginButton';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

const Home: NextPage = () => {
  return (
    <div className="flex min-h-screen-y flex-col items-center justify-center py-40">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main role={'main'} className="flex min-h-screen-y flex-col items-center justify-center gap-y-40 py-40">
        <h1 role={'heading'} className="text-40">
          Welcome to{' '}
          <a href="https://nextjs.org" className="!text-green">
            Next.js!
          </a>
        </h1>
        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        <LoginButton />
      </main>
    </div>
  );
};

export default Home;
