on:
  pull_request:
    types: [opened, synchronize]
jobs:
  test:
    runs-on: ubuntu-22.04
    name: Run Prettier and ESLint and tsc
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org
          cache: pnpm
      - run: pnpm install
      - run: pnpm lint
